openapi: 3.0.0
info:
  title: Plaid Workflow Backend API
  version: 1.0.0
  description: OpenAPI specification for backend API endpoints related to the Plaid workflow
paths:
  # Ping endpoint
  /ping:
    get:
      summary: Ping endpoint
      x-hero-handler: 
        id: ping
        action: pong
      responses:
        '200':
          description: Success

  /plaid/link/initiate:
    post:
      summary: Initiate Plaid Link
      description: Endpoint to initiate the Plaid Link flow
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/InitiatePlaidLinkRequest'
      responses:
        '200':
          description: Successfully initiated Plaid Link
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiatePlaidLinkResponse'
        '400':
          description: Bad request
  
  /plaid/token/exchange:
    post:
      summary: Exchange Token
      description: Endpoint to exchange public token for access token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenExchangeRequest'
      responses:
        '200':
          description: Token exchange successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenExchangeResponse'
        '400':
          description: Bad request

  /plaid/data/retrieve:
    get:
      summary: Retrieve Financial Data
      description: Endpoint to retrieve financial data using access token
      parameters:
        - name: access_token
          in: query
          description: Access token obtained from Plaid
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Financial data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialDataResponse'
        '400':
          description: Bad request

components:
  schemas:
    InitiatePlaidLinkRequest:
      type: object
      properties:
        userId:
          type: string
          description: User ID initiating the process
      required:
        - userId

    InitiatePlaidLinkResponse:
      type: object
      properties:
        linkToken:
          type: string
          description: Token for initiating Plaid Link UI
      required:
        - linkToken

    TokenExchangeRequest:
      type: object
      properties:
        publicToken:
          type: string
          description: The public token obtained from Plaid Link
        userId:
          type: string
          description: User ID associated with the token exchange
      required:
        - publicToken
        - userId

    TokenExchangeResponse:
      type: object
      properties:
        accessToken:
          type: string
          description: The access token for accessing financial data
      required:
        - accessToken

    FinancialDataResponse:
      type: object
      properties:
        transactions:
          type: array
          items:
            type: object
            properties: {}
        accounts:
          type: array
          items:
            type: object
            properties: {}
